export const ERROR_CODES = {
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    NO_TOKEN: 'NO_TOKEN',  
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    INVALID_TOKEN: 'INVALID_TOKEN',

    USER_NOT_ACTIVE: 'USER_NOT_ACTIVE',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    
    CANNOT_FIND_QUESTION: 'CANNOT_FIND_QUESTION',
    NO_QUESTION_FOUND: 'NO_QUESTION_FOUND',
    QUESTION_ALREADY_EXISTS: 'QUESTION_ALREADY_EXISTS',

    SERVER_ERROR: 'SERVER_ERROR',
    NOT_FOUND: 'NOT_FOUND'
  };